const posts = [
    {
        "id": 24,
        "post_uid": "61c453cb6baee",
        "title": "Eric Omondi Leaves Netizens Talking With New Hairstyle",
        "slug": "eric-omondi-leaves-netizens-talking-with-new-hairstyle",
        "summary": "Eric Omondi’s conspicuous change of hairstyles is not a new thing to us. Just like the comedian he is, his hairstyles depict further his bubbly nature.",
        "body": "Eric Omondi’s conspicuous change of hairstyles is not a new thing to us. Just like the comedian he is, his hairstyles depict further his bubbly nature. The jester not only comes out in unique outfits; but also cross-dresses better than your main chick!\n\nHis numerous change of hairstyles over the years have tickled netizens on some occasions- where he does it like a pro.\n\nHis hairstyles are always unique and this time, he has rocked in different colors-I don’t exactly know what to call this new style.\n\nIn relation to this, Eric has released a new video in the same hairstyle; threatening Jamaican Dancehall artist Konshens.\n\n    ”Should I release this Video and Finish Konshen’s Career or Should I Forgive him??? If you want me to release Comment “FINISH” and if you want me to Spare him Comment “FORGIVE”. HOLD MA BEER?”\n\nTheir beef was all about curtain raising claims and went on for weeks. Below are more hairstyles of the comedian over the years.\n\n \n",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-22T21:00:00.000Z",
        "pic": "Screenshot_20211210_135815.png"
    },
    {
        "id": 26,
        "post_uid": "61c58cda2b357",
        "title": "Uhuru hosts party for kids in Nairobi state house,X-mas came hurry for them  ",
        "slug": "uhuru-hosts-party-for-kids-in-nairobi-state-house-x-mas-came-hurry-for-them",
        "summary": "The kids were treated to fun activities such as live music, bouncing castles, face painting, skating, and video games among others.",
        "body": "The kids were treated to fun activities such as live music, bouncing castles, face painting, skating, and video games among others.President Uhuru Kenyatta and first lady Margaret Kenyatta treated hundreds of kids to an early Christmas party at State House. \n\nOn Sunday, the children of State House staff and those from selected Children`s homes were treated to fun-filled activities at State House. \n\nThe kids were treated to fun activities such as live music, bouncing castles, face painting, skating, and video games among others.\n\nUhuru and Margaret graced the event in style, and danced alongside the kids. \n\nTo mark the event, State House sparks filled the air at State House grounds. It has been a tradition for the Head of State to throw the Christmas party at this time of the year.\n\nHowever, the party was not hosted in 2020 in order to curb the spread of Covid-19. \n\nHere are photos of the event. ",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-23T21:00:00.000Z",
        "pic": "uhunye.jpg"
    },
    {
        "id": 27,
        "post_uid": "61c82704e5d6e",
        "title": "Socialite Huddah Monroe selling her womb for millions",
        "slug": "socialite-huddah-monroe-selling-her-womb-for-millions",
        "summary": " Huddah says she can only conceive a baby for a man at a fee and not get married to him.",
        "body": " Huddah says she can only conceive a baby for a man at a fee and not get married to him. Any man that wants to get a child with socialite Huddah Monroe will have to part with millions of dollars. \n\nIn her Instastories, Huddah revealed her womb is up for sale and it will cost 1,000,000 dollars. \n\nThis is approximately 100 million shillings just for you to get a baby with her. \n\n\"I am selling my womb, usd 1,000,000 to be your baby momma. Child support we shall agree while we conceive,\" she wrote. \n\nHuddah added that she can only conceive a baby for a man at a fee and not get married to him. \"Marriage can only last if you are married to Jesus Christ himself. I am ready to be a baby momma to a king who wants an ovary donation, no strings attached,\" she explained. \n\nThe socialite said she does not believe in marriage since it is not working in this generation. She would rather date someone for life. \n\n\"You all know marriage is a scam in this era of bamba with big boys and big/ small nyash and y`all getting into it, lol! why lie to each other? Just date until jesus christ comes back, save yourself the drama. \"",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-25T21:00:00.000Z",
        "pic": "huddah.jpg"
    },
    {
        "id": 28,
        "post_uid": "61c8285ef1b38",
        "title": "Kila mtu ako na pombe? Hilarious list of drunk escapades",
        "slug": "kila-mtu-ako-na-pombe?-hilarious-list-of-drunk-escapades",
        "summary": "Here are self-care tips as you celebrate Christmas and the New Year especially since alcohol will be involved.",
        "body": "Here are self-care tips as you celebrate Christmas and the New Year especially since alcohol will be involved.\n\n1. Symptom: Cold and humid feet.\n\nCause: Glass is being held at an incorrect angle (You are pouring the Drink on your feet).\nCure: Maneuver glass until open end is facing upward...\n\n2. Symptom: The wall facing you is full of lights.\n\nCause: You`re lying on the floor.\n\nCure: Position your body at a 90-degree angle to the floor.\n\n3. Symptom: The floor looks blurry.\n\nCause: you are looking through an empty glass.\n\nCure: Quickly refill your glass!\n\n4. Symptom: The floor is moving.\n\nCause : You`re being dragged away.Cure: At least ask where they`re taking you!\n\n5. Symptom: You hear echoes every time someone speaks.\n\nCause: You have your glass on your ear and trying to drink from it.\n\nCure: Stop making a fool of yourself, position your glass correctly.\n\n6. Symptom: Your wife and all your kids are looking funny.\n\nCause: You`re in the wrong house.\n\nCure: Ask if they can point you to your house.\n\n7. Symptom: The room is shaking a lot, everyone is dressed in white and the music is very repetitive.\n\nCause: You`re in an ambulance.\n\nCure: Don`t move. Let the professionals do their job.",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-25T21:00:00.000Z",
        "pic": "pombe.jpg"
    },
    {
        "id": 29,
        "post_uid": "61c829fba2778",
        "title": "`2021 was definately my year!`shouts Corazon Kwamboka",
        "slug": "`2021-was-definately-my-year!`shouts-corazon-kwamboka",
        "summary": " It is in 2021 that Corazon`s baby daddy Frankie JustGymIt proposed to him during their vacation in Zanzibar. ",
        "body": " It is in 2021 that Corazon`s baby daddy Frankie JustGymIt proposed to him during their vacation in Zanzibar. \n\nCorazon Kwamboka says her life was full of blessings in 2021. \n\nThis year, Corazon says she was happy to watch her son take his first step and also get pregnant with her second-born child. \n\nIt is in 2021 that Corazon`s baby daddy Frankie JustGymIt proposed to him during their vacation in Zanzibar. \n\n\"2021 I can say was definitely my year! Full of so many ups. From seeing my son take his first steps and turn a year old to getting engaged to the love of my life, to having my second child; a daughter this time. I had some lows too but the highs definitely top. Can`t wait to see what 2022 has in store for me. Merry Christmas and happy new year to you all,\" Corazon Kwamboka shared. ",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-25T21:00:00.000Z",
        "pic": "corazon.jpg"
    },
    {
        "id": 30,
        "post_uid": "61c82c9aac84c",
        "title": "Lilian Ng`ang`a posts cryptic message online",
        "slug": "lilian-ng`ang`a-posts-cryptic-message-online",
        "summary": "Former Machakos first lady Lilian Ng`ang`a has been posting cryptic messages.\n\nThe recent one is about how unimpressed she is with stuff that impresses most people.",
        "body": "Former Machakos first lady Lilian Ng`ang`a has been posting cryptic messages.\n\nThe recent one is about how unimpressed she is with stuff that impresses most people.\n\nLillian is known for her business acumen and knack for strategy.Most people assume that she is a pampered babe who loves the soft life.\n\nWell far from it. She is a salt of the earth kinda girl.\n\nShe reinforced this premise when she took to her social media and wrote, \"While you hit a certain age, you become permanently unimpressed by a lot of sh*t.\"\n\nLilian added, \"...and I absolutely love it.\"\n\nShe loves the little pleasures of life.\n\nA while back she gushed about rapper Juliani cooking for her \"soft\" and delicious chapatis.\n\nAnother time she posted about basking in the \"Sunday sun\" with the one she loves.\n ",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-25T21:00:00.000Z",
        "pic": "lilian.jpg"
    },
    {
        "id": 31,
        "post_uid": "61c82e26b4006",
        "title": "Omah Lay to perform in Mombasa on New Year`s eve",
        "slug": "omah-lay-to-perform-in-mombasa-on-new-year`s-eve",
        "summary": " The event dubbed `B-club Beach Festival` will see the Nigerian singer entertain fans on new years eve and usher them into 2022 in style.",
        "body": " The event dubbed `B-club Beach Festival` will see the Nigerian singer entertain fans on new years eve and usher them into 2022 in style. Nigerian singer Omah Lay is set for his second tour to Kenya this year. \n\nOn December 31, Omah Lay will treat fans to a live performance at Bungalows road, Nyali beach in Mombasa. \n\nThe event dubbed `B-club Beach Festival` will see the Nigerian singer entertain fans on new years eve and usher them into 2022 in style. \n\nAn early bird ticket for this event is going for Ksh 1,500, a regular for Ksh 2,000 while a VIP will cost 3,500. \n\nThis will be Omah Lay`s second tour in Kenya this year. In October, Omah Lay was in Kenya for the Pizza and Wine festival. \n\nThen, the `Understand` hit maker said he is in love with his Kenyan fans due to their support on his career. \n\n\"The love so far has been amazing and I am happy to be here. I wanted to come to Kenya because I get so much love here. I have a lot of fans.\n\nI want to connect with my fans, it`s not just about the money or publicity. I know I have so many fans in Kenya, I will do whatever to connect with them,\" said Omah Lay.",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-25T21:00:00.000Z",
        "pic": "omah.jpeg"
    },
    {
        "id": 32,
        "post_uid": "61c82fea8c9af",
        "title": "Anita Soina says her year was full of challenges as she celebrates a new one",
        "slug": "anita-soina-says-her-year-was-full-of-challenges-as-she-celebrates-a-new-one",
        "summary": "Environmental activist Anita Soina has ushered in her new year as she anticipate its gonna be a different one.",
        "body": "Environmental activist Anita Soina has ushered in her new year as she anticipate its gonna be a different one.\n\nShe is celebrating her 22nd birthday today.\n\nTaking it to her social media, Soina recounted how bad her 21 year was full of challenges.She said the year came with challenges, tears,pain, difficulties and everyday bullying but also she appreciates all the positives.\n\nAnita was the lady who was at the center of Terence Creative cheating scandal in 2019.\n\nShe added that despite the negativities, she has learnt that to be in charge of her happiness.\n\n\"Happy 22nd birthday to me. 21 wasn`t easy at all. It came with challenges, tears,pain, difficulties and everyday bullying but I appreciate all the positives.\n\nFrom mentors, mentees, achievements, networks, lessons, teamwork , love and happiness etc.\n\nOne thing I have learnt all this years is that you are in charge of your happiness, you are the one to wake up and make it happen and it’s how you react to tough situations that define you.\n\nLastly, don`t pay attention to the noise. It`s always people who don`t know you or have never met you or are bitter about their own lives that wake up and instead of working on themselves, they give negative opinions about you.\n \n\n\n",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-25T21:00:00.000Z",
        "pic": "anita.jpg"
    },
    {
        "id": 33,
        "post_uid": "61c8322251fda",
        "title": "Vera Sidika responds to allegations that Mauzo is not her baby daddy",
        "slug": "vera-sidika-responds-to-allegations-that-mauzo-is-not-her-baby-daddy",
        "summary": "Socialite Vera Sidika has come out to respond to allegations that her daughter was not fathered by her hubby Brown Mauzo.",
        "body": "Socialite Vera Sidika has come out to respond to allegations that her daughter was not fathered by her hubby Brown Mauzo.\n\nAccording to some of her fans, Asia Brown was sired by a white man because of her curly hair.\n\nTaking it to her social media, the mother of one said her cute daughter inherited her curly hair from her dad`s side.\n\n\"First thing that shook me when I gave birth to her was her hair! It was full and very curly. The nurses at the hospital were all wowed,\" she said.\n\nShe added;\"My baby is so blessed with good long, curly hair. She is two-month-old and can almost hold a ponytail. Hubby`s grandma has this exact same texture of hair and is extremely long. Hubby`s cousins have the same hair. It`s safe to say she inherited from that side because my hair is a struggle.\"\n\nVera unveiled her daughter Asia Brown`s face for the first time, two months after she arrived early this week.\n\nIntroducing her to her social media in-laws, Vera Sidika shared an adorable photo of Asia in a princess-like brown dress and captioned it;\n\n\"God has given His piece of heaven to us. Meet Asia Brown.\"",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-25T21:00:00.000Z",
        "pic": "vera.jpg"
    },
    {
        "id": 34,
        "post_uid": "61c83421a2605",
        "title": "List of top Youtubers of 2021",
        "slug": "list-of-top-youtubers-of-2021",
        "summary": "YouTube has today released the most-watched videos by Kenyans in 2021. ",
        "body": "YouTube has today released the most-watched videos by Kenyans in 2021. YouTube End of Year Lists reveals popular videos uploaded and watched on YouTube.\n\nThe lists have this year been expanded to include breakout creators and top Shorts videos of the year.\n\n`TT Comedian meets SLAY QUEENS` video was the most-watched non-music video in Kenya followed by a satirical remix by Marshall Sum of the Sukari hit song- `Politicians Dance Challenge, Uhuru, Ng`ang`a, Atwoli, Ruto ` while Inka TV`s upload of a child singing a dirge during the burial of five children who died in an inferno came third.\nIn the music videos category, Tanzania`s songstress Zuchu`s `Sukari` hit song was the most-watched followed by `Baikoko` by Mbosso featuring Diamond while Kenya`s Otile Brown`s song featuring Jovial - `Such Kinda Love` came third.\n\nOthers were `Liar` by Willy Paul and Miss P, `Ndovu ni Kuu` by Krispah and Khaligraph,  `Shamra Shamra` by Joefes, Mejja, and Mbuzi Gang, `Nyumba Ndogo` by Zuchu and `Yalah` by Mbosso consecutively. \n\nTT Comedian, Mungai Eve, Thee Pluto, and Terence Creative registered the highest growth rate in subscriber numbers during the year and emerged as top creators and breakout creators.\n\nOther creators in the top creator`s category include Churchill Show, Tales of the Crazy Kennar, Tuko/Tuco - Kenya, Thee Pluto Show, Flaqo Raz, Terence Creative, Diana Bahati, and Jalango TV.\n\nFormer Tuko Talks host, Lynn Ngugi, Afrimax English, TrendsGirl, Emmanuella, popular comedian Vinnie Baite, and Dance98 Academy all appeared in the list of the fastest-growing YouTube Channels in Kenya in 2021. \n\nIn the YouTube Shorts videos category, Small Prince channel attracted the most views followed by World of Africa TV while SwagBoyQ came in the third position.\n\nShorts is YouTube`s new short-form video experience that allows users to create short, catchy videos using their mobile phones. Other creators with the most Shorts videos views were Twins of Russia, Candy Platter, Daniel Labelle, and Julius Dein consecutively.\n\nTop Creators \n\n    TT Comedian\n    Mungai Eve\n    Churchill Show\n    Tales of the Crazy Kennar\n    Tuko/Tuco - Kenya\n    Thee Pluto Show\n    Flaqo Raz\n    Terence Creative\n    Diana Bahati\n    Jalango TV\n\nBreakout/Fastest Rising Creators\n\n    TT Comedian\n    Mungai Eve\n    Thee Pluto Show\n    Terence Creative\n    Lynn Ngugi\n    Afrimax English\n    TrendsGirl\n    Emmanuella\n    Vinnie Baite\n    Dance98 Academy ",
        "category": "entertainment",
        "tag": "Entertainment",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-25T21:00:00.000Z",
        "pic": "diana.png"
    },
    {
        "id": 35,
        "post_uid": "61cef076a47c4",
        "title": "RIP! Desmond Tutu is dead",
        "slug": "rip!-desmond-tutu-is-dead",
        "summary": "South African anti-apartheid icon Desmond Tutu, described as the country`s moral compass, died on Sunday aged 90, President Cyril Ramaphosa said.",
        "body": "South African anti-apartheid icon Desmond Tutu, described as the country`s moral compass, died on Sunday aged 90, President Cyril Ramaphosa said.\r\n\r\n\"The passing of Archbishop Emeritus Desmond Tutu is another chapter of bereavement in our nation`s farewell to a generation of outstanding South Africans who have bequeathed us a liberated South Africa,\" he said in a statement.\r\n\r\nA tireless activist, he won the Nobel Peace Prize in 1984 for combatting white minority rule in his country.Famously outspoken, even after the fall of the racist apartheid regime, Tutu never shied away from confronting South Africa`s shortcomings or injustices.\r\n\r\nIt was Tutu who coined and popularised the term \"Rainbow Nation\" to describe South Africa when Nelson Mandela became the country`s first black president.",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "desmond.jpeg"
    },
    {
        "id": 36,
        "post_uid": "61cef89d75dbd",
        "title": "Grandpa duties! Raila Odinga enjoys train ride to Kisumu with grandson",
        "slug": "grandpa-duties!-raila-odinga-enjoys-train-ride-to-kisumu-with-grandson",
        "summary": "• Raila Odinga said the train ride reminds him of the sweet old days. ",
        "body": "\r\n\r\nODM leader Raila Odinga is in a Christmas mood, spending more time his family members. \r\n\r\nOn Wednesday, Odinga boarded the doomed Kisumu train with one of his grandchildren. \r\n\r\nThis, he said, reminds him of the old days when train rides were a common thing for commuters in Kenya. \r\n\r\n\"Nothing beats a nostalgic train ride than sharing it with one of my grandkids. The holiday season for me is all about spending time with family. I loved the short train ride into Kisumu this afternoon,\" Raila wrote alongside his pictures inside a train with one of his grandchildren.\r\nRaila Odinga`s maiden ride comes hours after the `doomed` commuter train that operates the Nairobi-Kisumu route stalled at Muhoroni. Several passengers were left stranded on Tuesday night after the train developed a mechanical problem. \r\n\r\nKenya Railways attributed the derailment of the scheduled passenger train service at the Tamu area in Muhoroni Kisumu County to heavy rains in the areas.\r\n\r\nAfter hours of staying in the cold, the train was ready to proceed with the journey at 10 PM. \r\n\r\n\"We wish to inform the public that the Kisumu bound train encountered a slight hitch occasioned by the heavy rains that earlier pounded the Muhoroni area. The issue has since been sorted out and the train is already on the way to Kisumu,\" Kenya Railways announced.",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "raila.jpg"
    },
    {
        "id": 37,
        "post_uid": "61cefd7ce8d57",
        "title": "\"SGR loses 2 million shillings daily,\"Wanjiru Gikonyo",
        "slug": "\"sgr-loses-2-million-shillings-daily,\"wanjiru-gikonyo",
        "summary": "•\"If the government is not able to pay that China loan, China will take over the port`s operations.\"Wanjiru Gikonyo",
        "body": "It has now emerged that the SGR is losing Ksh 200 million per day.\r\n\r\nThis is despite Kenya being overwhelmed by loans taken from different countries.\r\n\r\nDuring an interview with Kamene and Jalango on the Morning Kiss, TISA National Coordinator Wanjiru Gikonyo said.\r\n\"It was recently discovered that the government has used the Kenyan ports in Mombasa. If the government is not able to pay that China loan, China will take over the port`s operations. They did that in Zambia, the people were forced to kick out their president.\"Wanjiru added, \"The SGR is losing 200 million a day just running it but we are still running it. A good chunk of the China money disappeared.\"",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "gikonyo.png"
    },
    {
        "id": 38,
        "post_uid": "61cf01add857f",
        "title": "Wycliffe Oparanya declared Luhya spokesperson at Bukhungu II ",
        "slug": "wycliffe-oparanya-declared-luhya-spokesperson-at-bukhungu-ii-",
        "summary": "Kakamega Governor Wycliffe Oparanya was today declared the Luhya spokesperson at a political rally in Bukhungu Stadium, Kakamega County",
        "body": "Kakamega Governor Wycliffe Oparanya was today declared the Luhya spokesperson at a political rally in Bukhungu Stadium, Kakamega County.\r\n\r\nIn a declaration by Western Region Elders, Governor Oparanya was handed the powers to negotiate the community’s interest in the Azimio la Umoja movement.\r\n\r\n“Western elders unanimously hand over Oparanya as Luhya community leader with whom you [Raila Odinga] will negotiate the interest of the community in your government,” the declaration read.\r\n\r\nThe meeting dubbed Bukhungu II also resolved that the Luhya community will be part and parcel of the Azimio la Umoja Movement.The elders resolved to mobilise the community to support and vote for Raila in the 2022 General Election. The elders also declared that the Luhya community will only vote for candidates allied to Azimio la Umoja in other elective positions.\r\n\r\nIn 2016, when the Bukhungu I meeting was held in the same venue, ANC leader Musalia Mudavadi was declared the community spokesperson.\r\n\r\nMudavadi has so far declared to contest for Presidency in 2022 and skipped the meeting despite being invited by the organisers.\r\n\r\nWhile addressing the media on Tuesday, Cotu boss Francis Atwoli said Mudavadi was invited as the community’s spokesperson.\r\n\r\nPoliticians allied to Mudavadi led by Kakamega Senator Cleophas Malala dismissed the invitation, saying the meeting was a coronation exercise for Raila’s State House bid. ",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "wicliff.jpg"
    },
    {
        "id": 39,
        "post_uid": "61cf02839fbb1",
        "title": "UPF, UDA battle for Nakuru’s one million votes ",
        "slug": "upf,-uda-battle-for-nakuru’s-one-million-votes-",
        "summary": "As the August 2022 General Elections draw near, stakes are high in the vote-rich counties, among them Nakuru, which played an integral part in President Uhuru Kenyatta`s victory. ",
        "body": "n 2017, the county had 949,618 registered voters, which surpassed the one million mark following the registration of 58,436 new voters by November 2, 2021.\r\n\r\nWhile a majority of the incumbent elected leaders clinched their seats through the ruling Jubilee Party tickets, the battle to control a million votes is now between two new political outfits.\r\n\r\nGovernor Lee Kinyanjui recently formed a new political party Ubuntu People’s Forum (UPF), which he has embarked on a journey to popularize across the county.\r\n\r\nHowever, Deputy President William Ruto`s United Democratic Alliance (UDA) appears to be keen on countering Kinyanjui’s move if his recent forays are anything to go by.On October 9 and 10, Governor Kinyanjui took his campaigns to Naivasha and Gilgil, where he hosted opposition leader Raila Odinga.\r\n\r\nDuring the visit, Kinyanjui drummed support for Raila and termed him as the surest bet for Nakuru to find itself on the table for sharing the national cake after the next polls.\r\n\r\n“I am glad that Raila is of the idea that we need more youth in the cabinet and other leadership positions. Nakuru must produce a cabinet secretary for the first time since the 1960s,” said Kinyanjui.\r\n\r\nRaila assured the youth of inclusivity in his government if elected, adding that he would come up with policies promoting entrepreneurship among the youth.\r\n\r\n“We shall address the restoration of Lake Naivasha and create an environment for investments in the county. The youth must get a share of the opportunities in the upcoming industrial park in Naivasha,” said Raila. On November 9, DP Ruto toured the same areas during which he drummed support for his bottom-up economic model and dismissed claims that Raila had managed to make inroads in the region.\r\n\r\n“In our bottom-up strategy, we shall empower the youth as planned in the Big Four agenda. My priority shall be allocating funds to sectors that create jobs for the youth,” said Ruto in Gilgil.\r\n\r\nOn November 18 and 19, Governor Kinyanjui took his campaigns to Njoro sub-County, where he made stopovers in Tipis, Mau Narok, Mauche, Naishi, Bagaria, among other trading centres.\r\n\r\nDuring the tour, Kinyanjui launched Lari Vocational Training Centre, emphasizing the need to empower the youth with skills that would make them self-reliant and contributors to the economy.\r\n\r\nHe also campaigned for Raila and his new party, saying that UPF was a vehicle to place Nakuru on the negotiating table after decades of exclusion despite overwhelmingly supporting winning candidates.\r\n\r\n“The next government, which we must be part of, will focus on youth empowerment by imparting skills on them. Nakuru County has established an enterprise fund aimed at helping the youth in business,” said Kinyanjui.\r\n\r\nDP Ruto and his UDA brigade toured the areas on November 25, making six stopovers between Mau Narok and Njoro towns, during which they campaigned against UPF and Raila’s candidature.\r\n\r\n“I have heard some people claim that Nakuru is now behind ODM and its party leader. Is that true? Let Kinyanjui know that Nakuru will not go that direction but is behind UDA,” said Nakuru Senator Susan Kihika.\r\n\r\nKinyanjui took his campaigns to Subukia and Bahati on December 14, where he reiterated his commitment to growing UPF into a national party.\r\n\r\n“UPF belongs to Nakuru people. It is our small car that we should not dump for a bigger SUV that belongs to our neighbours. I will defend my seat on the UPF ticket. The party shall field candidates for all positions except the presidency for which we shall back Raila,” said Kinyanjui.\r\n\r\nOn December 18, Ruto returned to Nakuru, beginning his visit in Lanet, Bahati, before proceeding to Subukia town and Kabazi trading centre, where he called on the residents to vote for a UDA six-piece suit set of leaders in the coming polls.\r\n\r\nDuring the tour, Ruto allies led by Bahati MP Kimani Ngunjiri lashed at Kinyanjui for forming a new party, which according to him, aimed at splitting the votes in favour of Raila.\r\n\r\n“You have heard that our governor is now an affiliate of ODM with his new party. As Nakuru, we will not join ODM. We shall elect all UDA leaders starting from the top to bottom,” said Ngunjiri.\r\n\r\nNakuru Town West MP Samuel Arama has however come out to strongly defend Kinyanjui, terming Ruto’s campaigns as tracing Kinyanjui`s footsteps out of fear that UPF is now a threat to UDA.\r\n\r\n\"The DP is frustrated by the new party, which threatens to take a share of the one million votes. He and his lieutenants are out to scuttle progress made by Kinyanjui. Nakuru is big, but they are choosing to campaign where Kinyanjui visits days later,\" said Arama.\r\n\r\nThe second-term lawmaker who is yet to declare which party he will vie on said he would back Kinyanjui for the governorship position.\r\n\r\n\"Although Kinyanjui has formed a new party, he is allied to Azimio la Umoja dream. For that reason and the development he has achieved, I will support him regardless of the party he will vie on,\" said Arama. ",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "ruto.jpg"
    },
    {
        "id": 40,
        "post_uid": "61cf050672cb3",
        "title": "Leaders pile pressure on Mudavadi to honour Bukhungu invite ",
        "slug": "leaders-pile-pressure-on-mudavadi-to-honour-bukhungu-invite-",
        "summary": "\r\n\r\nSome leaders from the Western region are piling pressure on Amani National Congress party leader Musalia Mudavadi to attend the Bukhungu ll meeting tomorrow. ",
        "body": "Defence Cabinet Secretary Eugene Wamalwa is among the leaders determined to convince Mudavadi and Ford Kenya party leader Moses Wetang’ula to honour the invite.\r\n\r\nWamalwa said Mudavadi and Wetang’ula should spare time to attend the meeting, which he termed crucial and timely. “Let Mudavadi and Wetang’ula put their differences with other leaders aside and turn up at Bukhungu,” said Wamalwa, who was in Malava Constituency.\r\n\r\nHe also urged residents to attend the meeting in large numbers.\r\n\r\nWamalwa said the Bukhungu ll meeting would unite the Mulembe nation and the Western region at large. “To my brothers, Mudavadi and Wetang’ula, please come, let us reason together. The greatest change begins at the family table, and Bukhungu is our family reasoning table. Let’s come together and look at the future together and see which path to take,” he said.\r\n\r\nAccording to the CS, Bukhungu ll could give a solution to the deferred dream of Building Bridges Initiative (BBI) that can only be realised through Azimio la Umoja under Raila Odinga.\r\n\r\nWamalwa cautioned Kakamega Senator Cleophas Malala, saying that he has no authority to stop anyone from holding a meeting in Kakamega.\r\n\r\n“Kakamega is the headquarters of Mulembe nation and bedroom for all of us. Senator Malala cannot purport to own Kakamega.\r\n\r\n\"When you start chest-thumping or resort to divisive politics, you are proving that you are not a good leader,” Wamalwa said.\r\n\r\nDemocratic Action Party Kenya (DAP-K) party leader Wafula Wamunyinyi, who accompanied Wamalwa, said the outfit was gaining momentum.\r\n\r\n“As a party, we are ready to work with Raila under the Azimio la Umoja movement. Those who keep off Bukungu will have themselves to blame,” he said.  ",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "wamalwa.jpg"
    },
    {
        "id": 41,
        "post_uid": "61cf05c536b6b",
        "title": "MP Bernard Koros undergoes surgery after being punched in parliament ",
        "slug": "mp-bernard-koros-undergoes-surgery-after-being-punched-in-parliament-",
        "summary": "\r\n\r\nSigowet-Soin MP Bernard Koros has undergone minor surgery at Nairobi Hospital following an eye injury he sustained during Wednesday`s scuffle in parliament. ",
        "body": "According to his friend and colleague, Belgut MP Nelson Koech, a delay in taking him to the hospital would have led to serious damage to his cornea and lower eyelid.\r\n\r\n“The injury was deep. He is bespectacled so the punch broke his glasses and some of the shards entered his eyes while others cut his lower eyelid,” said Koech who visited the Koros this morning. A picture shared by Koech on social media showed Koros in a hospital bed with a bandage on his right eye. \r\n\r\n“He is out of danger,” assured Koech. \"I am ashamed that something like that can happen in an honourable house.” \r\n\r\nFollowing the fistfight during the debate on the controversial Political Parties (Amendment) Bill, 2021, Luanda MP Chris Omulele, who was chairing the session, suspended Minority Leader John Mbadi from the House for five days over his alleged involvement.\r\n\r\nAddressing the press after being ejected from the House, Mbadi claimed that Koros bit his finger after he warned him against voting for an absent MP. \r\n\r\n“I could not bite him back and decided to respond in another way. I was defending myself and the person defending himself has been kicked out,\" said Mbadi.\r\n\r\nThe Bill is set to be brought before Parliament on January 5, 2021. ",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "ben.jpg"
    },
    {
        "id": 42,
        "post_uid": "61cf0708384d4",
        "title": "Somalia, AU agree to review Amisom transition plan ahead of deadline",
        "slug": "somalia,-au-agree-to-review-amisom-transition-plan-ahead-of-deadline",
        "summary": "Somalia and the African Union on Thursday agreed to have their respective technical teams re-examine the future of the combat mission, Amisom, whose mandate was extended recently to the end of March 2022.",
        "body": "\r\n\r\nAnd in a show of compromise, the two sides, who have recently haggled over what form the African Union Mission in Somalia (Amisom) should take, appeared to agree on the basics, including predictable funding and a focus on Al-Shabaab and other terror merchants in Somalia.\r\n\r\nAt a meeting between Somalia’s federal government, the African Union Commission (AUC) and Amisom representatives, it was generally agreed that technical teams begin discussions from January 10 for 30 days.\r\n\r\nThe teams will then resubmit their report to the African Union Peace and Security Council from February 11, to inform the actual format the mission will take.\r\nMogadishu meeting\r\n\r\nThe decision, indicated in a joint communique on Thursday, came after the AUC delegation, led by Alhaji Sarjoh Bah, director of conflict management, met in Mogadishu with Somali government officials, including federal minister for defence Abdulkadir Mohamed Nur and his internal security counterpart Abdullahi Mohamed Nor.\r\n\r\nThe meeting was also attended by the Amisom boss, Mozambican diplomat Francisco Madeira, and other Amisom senior military officials.\r\n\r\nIt was crucial because Amisom’s mandate, which was last week extended by the UN Security Council by three months, appeared to expire without a formal agreement on what will replace it.\r\n\r\nThey agreed that Somalia will resubmit its Transition Plan, a document initially tabled at the AU Peace and Security Council in February, arguing that Amisom stay on until 2023, as Mogadishu gradually picks up the duties of protecting liberated areas.\r\n\r\nThey also agreed that a joint technical team composed of officials from the Federal Government of Somalia and the African Union resume discussions on January 10 and finish by February 2022.\r\n\r\nBoth sides, the communique said, recognise “the need for a reconfigured AU transition Mission in Somalia to have a practicable and sustainable funding mechanism”.\r\nFight Al-Shabaab\r\n\r\nAmisom was created in 2007 to fight Al-Shabaab, but more than 13 years the threat from the militants persists. While both sides acknowledge the mission’s role in driving the Shabaab from crucial cities such as Mogadishu and Kismayu, Somalia argues it needs to start taking over responsibility by improving the capacity of its own troops.\r\n\r\nThe AU, though, appeared wary of a quick handover, citing the existing threat from the Shabaab, which still controls a significant chunk of the countryside. In October, the AU Peace and Security Council accepted one of the four recommendations tabled by an independent technical team hired by the AU earlier in June.\r\n\r\nThe council endorsed a hybrid mission to take over from Amisom, and which would be funded by the UN and include troop contributors from UN member states, as well as segments for technocrats and other institution-rebuilding experts.\r\nScepticism\r\n\r\nThis suggestion, though endorsed by the five troop contributors - Kenya, Ethiopia, Djibouti, Ethiopia, Burundi and Uganda - has been met with scepticism from some UN Security Council members because of concerns about funding.\r\n\r\nOn Thursday, the Somalia government agreed with the AU to discuss the transition plan only based on principles that will place the continental body in the central role, respect Somalia’s leadership of the transition and provide for adequate funding to defeat Al-Shabaab.\r\n\r\nThey also agreed that Amisom or whatever replaces it must work within international law and be accountable to financiers, troop contributors and the public it serves.\r\n\r\n ",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "ami.jpg"
    },
    {
        "id": 43,
        "post_uid": "61cf08a18b1e6",
        "title": "Luhya elders back Raila’s presidential bid – Nairobi News",
        "slug": "luhya-elders-back-raila’s-presidential-bid-–-nairobi-news",
        "summary": "A section of Luhya elders has declared support for the Azimio la Umoja movement.",
        "body": "A section of Luhya elders has declared support for the Azimio la Umoja movement.\r\n\r\nIn a highly charged event held at the Bukhungu Stadium in Kakamega, the elders explained that the movement which is led by veteran politician Raila Odinga was the community’s safe bet ahead of the 2022 polls.\r\n\r\nOdinga has declared his interest in succeeding President Uhuru Kenyatta ahead of the August polls, and is expected to face stiff opposition from among others Deputy President William Ruto and former vice president Musalia Mudavadi.\r\n\r\nMeanwhile, the elders have also vowed to mobilize the community to rally behind Odinga.\r\n\r\n“We resolve to form the next government with Raila Odinga and that the community shall only vote for candidates on other seats who are allied to Azimio la Umoja.”\r\n\r\nAlso present at the event were scores of political leaders, including Jubilee party secretary-general Raphael Tuju, Defence Cabinet Secretary Eugene Wamalwa, Kakamega governor Wycliffe Oparanya, COTU boss Francis Atwoli plus more than 30 MPs and Senators.\r\n\r\nThe elders also named Kakamega Governor Wycliffe Oparanya as the community leader to negotiate on behalf of the community\r\n\r\nBut Mudavadi and Ford-Kenya supremo Moses Wetangula were among those that skipped the event.",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "rao.jpeg"
    },
    {
        "id": 44,
        "post_uid": "61cf0a4b40078",
        "title": "Raila is not government project, Kamanda tells off Ruto",
        "slug": "raila-is-not-government-project,-kamanda-tells-off-ruto",
        "summary": "Nominated MP, Maina Kamanda has told off Deputy President William Ruto, asking him to stop calling ODM leader Raila Odinga a state project.",
        "body": "Nominated MP, Maina Kamanda has told off Deputy President William Ruto, asking him to stop calling ODM leader Raila Odinga a state project.\r\n\r\nSpeaking at the Bukhungu Stadium on Friday, Kamanda said that Raila has lost election three times, and it is his time to lead the country, to help it achieve what he has always wanted to do for the people.\r\n\r\n“Ruto you have to lose elections for about two or three times before taking over as a president,” Kamanda said.\r\n\r\nThe MP said Raila currently has the key to state house and he will clinch the top seat in August 2022.\r\n\r\nFormer Gatanga MP, Peter Kenneth who also spoke at the event said Raila is the only leader who can run this country peacefully.\r\n\r\nHe went on to say that Kenyans need a leader who is not threatening and chest thumping because this country will be ruined if left in bad hands, calling on people to vote for Raila Odinga.\r\n\r\n“Elect Raila Odinga but don’t make the mistake of choosing Ruto,” he said.\r\n\r\nTeso North MP, Ouko Kaunya urged ANC party leader Musalia Mudavadi to join Azimio la Umoja which he termed as the only vehicle that has the capacity to deliver on the ballot.\r\n\r\n“I have come here a head of my party leader to ensure everything is in order to when he arrives,” Kaunya said.\r\n\r\nHe said Raila is the only one with the capacity to face off with Ruto on the ballot and he is at Bukhungu Stadium to ensure the interest of Teso people are represented.\r\n\r\nKaunya was elected on an ANC party ticket in 2017. The law maker has hinted at joining Azimio la Umoja.",
        "category": "news",
        "tag": "News",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-30T21:00:00.000Z",
        "pic": "kamande.jpeg"
    },
    {
        "id": 45,
        "post_uid": "61d02026548d0",
        "title": "Diana Marua deletes controversial YouTube video",
        "slug": "diana-marua-deletes-controversial-youtube-video",
        "summary": "Content creator Diana Marua has appeared to delete a video in which she is heard accusing singer Willy Paul of attempted rape.",
        "body": "The move comes days after a Nairobi court ordered her to pull down the video pending hearing and determination of a suit filed by Willy Paul, born Wilson Radido.The court order also prohibits anyone from sharing the video.\r\n\r\n“The accusations labeled against me have caused me untold suffering, financial loss, and my dignity as a father, the politics in the industry are dirty and it hurts me because it’s from people I regarded as a family,” explained Willy Paul via a statement on social media.\r\n\r\n“(The) Truth, Sun and the Moon can never be hidden Long. If you spend your time hoping someone will suffer the consequences for what they did to your heart, then you’re allowing them to hurt you a second time in your mind.”\r\n\r\nThe video titled “My untold story, Willy Paul attempted to rape me” caused a stir on social media with Kenyans sharing varying opinions.\r\n\r\nIn the 26-minute clip, Marua, wife to singer Kelvin Bahati, claims to have had a brief encounter with Willy Paul in the past where the incident happened.\r\n\r\nThe mother of two further claims the events took place before she got married to the singer.\r\n\r\nWilly Paul has repeatedly refuted the allegations.In the order issued on December 29, 2021, Milimani Commercial Court’s Senior Principal Magistrate, D.W Mburu, directed Diana Marua to remove a video she published on her YouTube channel.\r\n\r\nThe directive was in response to an application filed by the singer through her lawyer a week earlier.\r\n\r\nWilly Paul said his health had deteriorated and had also suffered financial losses as a result of the incriminatory video.\r\n\r\nJustice Mburu warned that non-compliance with the order would have legal repercussions.",
        "category": "gossip",
        "tag": "Gossip",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "diana b.png"
    },
    {
        "id": 46,
        "post_uid": "61d021da72da4",
        "title": "TV journalist Nana Owiti shares couple goals",
        "slug": "tv-journalist-nana-owiti-shares-couple-goals",
        "summary": "TV presenter Nana Owiti and rapper husband King Kaka are fast becoming one of the most admired couples on the entertainment scene.",
        "body": "The lovebirds are known to have navigated through challenging spells in their relationship and emerged stronger.nd thus Owiti, in a recent question and answer session on her Instagram page, lifted the lid on the secrets of her this success, at a period their peers are struggling to remain in love.\r\n\r\n“Rome was not built in a day,” she explained while calling for patience and understanding.\r\n\r\n“For a relationship to work, you must put in the sacrifice, compromise, love, care, gentleness, and a whole lot of forgiveness. Remember lust rushes and love waits. If you walk into a relationship thinking love is enough baby that’s wishful thinking.”\r\n\r\n“Communication is the key to a successful relationship,” she adds.\r\n\r\n“Well, destroy that thinking. Comprehension is. You can communicate all you want but if the other party is not comprehending what you are saying then it’s just noise. In through one ear, and out through the other.”\r\n\r\nEarlier in the year, Nana revealed that she’d dumped King Kaka after he cheated on her with singer Sage Chemutai, an affair that led to pregnancy, all while Nana was also expecting the rapper’s first child.The couple separated for seven months before they decided to rekindle their love, after King Kaka, real name Kennedy Ombima, asked Nana for forgiveness.\r\n\r\nThe media personality and mother of two is a co-host at switch TV’s ChatSpot, a controversial show about current affairs in the entertainment industry. Nana also runs her online digital marketing work primarily through social media platforms such as Facebook and Twitter.\r\n\r\nOwiti has also been praised for standing by her better half at a time he was seriously sick.",
        "category": "gossip",
        "tag": "Gossip",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "nana.jpeg"
    },
    {
        "id": 47,
        "post_uid": "61d02362363a5",
        "title": "Socialite Amber Ray spotted hanging out with ex-hubby",
        "slug": "socialite-amber-ray-spotted-hanging-out-with-ex-hubby",
        "summary": "Socialite Faith Makau alias Amber Ray and ex-husband Jimal ‘Roho Safi’ Marlow have sparked mixed reactions after they were spotted enjoying a good time.",
        "body": "The former love birds, best remembered for a dramatic fling in 2021, were seen hanging out at a popular entertainment joint in Nairobi.In a video shared by singer KRG, Amber Ray is seen driving into the club in a Jeep with her ex-husband sitting next to her. This has invited suggestions the couple could still be an item, or, maybe, just friends.\r\n\r\nThe duo has always maintained their relationship remains platonic after their fallout.\r\n\r\nHowever,  trouble started when Jimal, the Matatu Operators Association chairman, crossed the line with his wife Amira when he recently posted his ex-wife on his Instagram page on her birthday.\r\n\r\nThis promoted Amira to claim she is now a single mother while asking for a divorce citing disrespect.\r\n\r\nShe further stated that she should not be associated with her husband in any matter that surfaces about him on social media.\r\n\r\nMeanwhile, the scuffles between Amira and Amber have been in the public eye for quite some time.\r\n\r\nAt some point, the ex-co wives shared not-so-pleasant messages about each other on social media with Jimal seemingly not in control of the situation.This isn’t the first time that Jimal and his ex-wife have been spotted hanging out. A photo of the two spending time at the Coast almost a month after their split in July 2021 surfaced online, causing a stir among netizens about where the businessman’s heart is.\r\n\r\nAmber and Jimal started dating in December 2020 and got married in an Islamic-themed wedding in March 2021, a marriage that was short-lived as they divorced barely six months later.\r\n\r\nAmira and Jimal have been married for seventeen years now and together have been blessed with two sons.",
        "category": "gossip",
        "tag": "Gossip",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "amber r.jpg"
    },
    {
        "id": 48,
        "post_uid": "61d0241c8358e",
        "title": "Sauti Sol’s Chimano celebrates ‘love of his life’ Bein",
        "slug": "sauti-sol’s-chimano-celebrates-‘love-of-his-life’-bein",
        "summary": "Sauti Sol singer Austin Chimano has lit up social media with his birthday message to fellow singer and band member Bien Aime Barasa.",
        "body": "Chimano shared a picture of Bien with a short message referring to him as the love of his life.“Happy birthday to the love of my life! @bienaimesol Love you to the moon and back infinity!” tweeted Chimano.\r\n\r\nThe message riled mixed reactions from Kenyans on Twitter who mostly expressed confusion.\r\n\r\nChimano recently came out as being a member of the LGBTQ community. Speaking to a local media house he insisted he was tired of living a lie and had decided to start living his life without fear.\r\n\r\nHis latest solo hit “Friday Feeling” he said was a true manifestation of himself and living life without any reservations.\r\n\r\nKOT could not help but start speculating on whether Bien might also be a member of the LGBTQ community.\r\n\r\nBien married fitness trainer Chiku last year in a private invite-only ceremony.\r\n\r\nSince their union, the couple made headlines earlier this year after Bien made claims during the bands reality show “Sol family” that suggested he is in an open marriage.",
        "category": "gossip",
        "tag": "Gossip",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "sauti.jpg"
    },
    {
        "id": 49,
        "post_uid": "61d0294f8d7f0",
        "title": "Lesbian Makena Njeri lands new bae",
        "slug": "lesbian-makena-njeri-lands-new-bae",
        "summary": "Is singer Karen Kaz the new partner of former journalist Makena Njeri?\r\n\r\nAnd is she also the reason for her split up with her entrepreneur Mitchell Ntalami?",
        "body": "Well, Kenyans online seem to think so if this post by Karen is anything to go by.\r\n\r\nKaren wrote a sweet message to Makena thanking her for coming into her life and nudging her in the right direction.\r\n\r\nShe also thanked her for being patient with her and showing her warmth, understanding, peace, and love.\r\n\r\n“Fada ghad! I dey tenk you!! This littu pumpkin of mine came into my life at a time when I literally was looking in the opposite direction but didn’t know that I needed them. They have been light, warmth, understanding, peace and love,” Karen Kaz said.\r\n\r\n“I am grateful I get to experience different kinds and varieties of love in my life. because I’m not one to hold out on love. Ask those that know me!!! So @makenanjeri Chris, pumpkin, Malenege ?. Nakumind sana! Thank you for being patient with me… I know we will grow into the highest divinity!! And I’m here for the ride!\r\n\r\nI love you ❤️,” she added.Makena then responded with her own romantic message.\r\n\r\n“My carrot ?. The garden is looking up ?. Thank you for all the beautiful affirmations and love that you have brought into my life! Kazy Kaz you have a soul. I love you ❤️ Also who is malenge?” replied Makena.\r\n\r\nThe public show of affection comes a few weeks after Makena was involved in a nasty breakup with long-time girlfriend Mitchell Ntalami.\r\n\r\nNtalami accused Makena of ‘serial infidelity’ with multiple partners including a public figure.\r\n\r\nShe claimed that the reason she decided to air their dirty laundry was for her own sanity as she was slowly losing her mind with numerous questions from fans and friends on why she is no longer seen hanging out with Makena or posting pictures of the two of them together on social media.",
        "category": "gossip",
        "tag": "Gossip",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "makena.jpg"
    },
    {
        "id": 50,
        "post_uid": "61d02b4269f37",
        "title": "Vlogger Natalie Tewa shares Covid-19 experience",
        "slug": "vlogger-natalie-tewa-shares-covid-19-experience",
        "summary": "Travel and lifestyle vlogger Natalie Tewa has shared her experience after testing positive for Covid-19.\r\n\r\nShe shared the news via her Instagram stories while also adding her surprise considering she’s always been extra cautious and had already received both doses of the Moderna vaccine.",
        "body": "“I’ve just tested positive for Covid. I’ve been avoiding Covid for so long, I was literally the Covid police, saying wear your mask, don’t go out. Now I went out for my birthday on Friday, and the place was super crowded but of course, you’re already there and having fun,” she explained.\r\n\r\n“The friends I was with are down, not feeling so well, so I knew I had to test. I got my first symptoms on Monday. I was having body aches, feeling feverish, headache, and basically fatigued. The results came in today and I’m positive for Covid, although I am feeling a bit better, just congestion in the nose and coughing which I’m taking medication for,” she added.\r\n\r\nThe content creator shared advice saying everyone should be extra cautious this festive season, more so because with the lift of lockdown and curfew, many people are moving up and about. “Please guys be very careful. Stay safe especially if you are perambulating the streets this December. The virus is spreading a lot faster because everyone is going out,” she said.Besides the medical setback, the vlogger has had her fair share of online trolling and negativity on social media that forced her to go low-key for six months, from July 2020 to January 2021, and when she resurfaced explained to her fans why she had ghosted her online presence.\r\n\r\nShe has since been actively posting new content on her YouTube and Instagram in regards to travel and lifestyle, which also includes hair and skincare routines.\r\n\r\nThe curvy influencer was also recently shortlisted in the Top 100 most influential young Kenyan personalities list, in view of her massive online following generated from her content.\r\n\r\nMs. Tewa is undeniably viewed as an epitome of beauty with brains as she equally doubles as an architect, having graduated in 2016 from the University of Leeds with a degree in Architectural Engineering.",
        "category": "gossip",
        "tag": "Gossip",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "natalie.jpg"
    },
    {
        "id": 51,
        "post_uid": "61d02c3d9846d",
        "title": "Socialite Corazon Kwamboka welcomes baby number two",
        "slug": "socialite-corazon-kwamboka-welcomes-baby-number-two",
        "summary": "Socialite Corazon Kwamboka has welcomed her second child.\r\n\r\nShe shared the news with her fans on social media with a picture of herself cradling her newborn, a baby girl.",
        "body": "“Zero-hours of labor, 1hr 15 mins inside the theatre, and 6 hours of lying on my back with drips and chills, unable to twist or turn, I am finally holding my little girl. Thank you for choosing us to be your parent’s koko. We can’t wait to show you the world and love you forever,” wrote Corazon.\r\n\r\nCorazon is engaged to fitness trainer Frank Kiarie, aka Frankie Just Gym It, who also is the father of her firstborn son.\r\n\r\nThe couple announced that they were expecting their second child in September.\r\n\r\nHe posted a family photo revealing Kwamboka’s growing baby bump with the caption, “And the family keeps growing! We can’t wait to meet you.”\r\n\r\nThe news of the pregnancy came days after Frankie proposed to Kwamboka while holidaying in Zanzibar, and she said ‘Yes.”Frankie now becomes the father of four, as he already has two lovely boys with YouTuber Maureen Waititu.",
        "category": "gossip",
        "tag": "Gossip",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "corazon.png"
    },
    {
        "id": 52,
        "post_uid": "61d02f969f47e",
        "title": "How we used TikTok to trump President Trump",
        "slug": "how-we-used-tiktok-to-trump-president-trump",
        "summary": "So we all know who President Trump is. He is the president of “the greatest” country in the world.\r\n\r\nMany dislike him and just as many others adore him. Many teenagers, including myself, don’t like him at all.",
        "body": "His policies are out of order and his moral compass is clearly broken. But he manages to sway the older generations with economic and business-related manifestos and policies.\r\n\r\nSince many in our generation don’t like him, we decided to mess with his campaign.\r\n\r\nNow you may be wondering, “how did you do that?” Well… there’s this social media app called Tik Tok. It has over 750 million people using it worldwide.\r\n\r\nMostly, the app has kids dancing, making funny videos, doing skits, showing their art forms and showing their music skills. But…. the app is also used to spread awareness on issues in the world, such as the Black Lives Matter (BLM) movement.\r\n\r\nAnd lately, it has been used by young people to influence the upcoming election in the US. One creator came up with the idea to mess with President Trump’s campaign.",
        "category": "world",
        "tag": "World",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "trump.jpeg"
    },
    {
        "id": 53,
        "post_uid": "61d0318fb96d4",
        "title": "Germany shuts down half of its 6 remaining nuclear plants",
        "slug": "germany-shuts-down-half-of-its-6-remaining-nuclear-plants",
        "summary": "BERLIN -- Germany on Friday shut down half of the six nuclear plants it still has in operation, a year before the country draws the final curtain on its decades-long use of atomic power.",
        "body": "BERLIN -- Germany on Friday shut down half of the six nuclear plants it still has in operation, a year before the country draws the final curtain on its decades-long use of atomic power.\r\n\r\nThe decision to phase out nuclear power and shift from fossil fuels to renewable energy was first taken by the center-left government of Gerhard Schroeder in 2002. His successor, Angela Merkel, reversed her decision to extend the lifetime of Germany’s nuclear plants in the wake of the 2011 Fukushima disaster in Japan and set 2022 as the final deadline for shutting them down.\r\n\r\nThe three reactors now being shuttered were first powered up in the mid-1980s. Together they provided electricity to millions of German households for almost four decades.\r\n\r\nOne of the plants — Brokdorf, located 40 kilometers (25 miles) northwest of Hamburg on the Elbe River — became a particular focus of anti-nuclear protests that were fueled by the 1986 Chernobyl catastrophe in the Soviet Union.The other two plants are Grohnde, 40 kilometers south of Hannover, and Gundremmingen, 80 kilometers (50 miles) west of Munich.\r\n\r\nSome in Germany have called for the decision on ending the use of nuclear power to be reconsidered because the power plants already in operation produce relatively little carbon dioxide. Advocates of atomic energy argue that it can help Germany meet its climate targets for reducing greenhouse gas emissions.\r\n\r\nBut the German government said this week that decommissioning all nuclear plants next year and then phasing out the use of coal by 2030 won’t affect the country’s energy security or its goal of making Europe`s biggest economy “climate neutral” by 2045.\r\n\r\n“By massively increasing renewable energy and accelerating the expansion of the electricity grid we can show that this is possible in Germany,” Economy and Climate Minister Robert Habeck said.\r\n\r\nRenewable energy sources delivered almost 46% of the electricity generated in Germany in 2021. Coal accounted for more than 51%, while nuclear power provided over 13%, according to the Fraunhofer Institute.\r\n\r\nSeveral of Germany`s neighbors have already ended nuclear power or announced plans to do so, but others are sticking with the technology. This has prompted concerns of a nuclear rift in Europe, with France planning to build new reactors and Germany opting for natural gas as a “bridge” until enough renewable power is available, and both sides arguing their preferred source of energy be classed as sustainable.Germany`s remaining three nuclear plants — Emsland, Isar and Neckarwestheim — will be powered down by the end of 2022.\r\n\r\nWhile some jobs will be lost, utility company RWE said more than two-thirds of the 600 workers at its Gundremmingen nuclear power station will continue to be involved in post-shutdown operations through to the 2030s. Germany`s nuclear power companies will receive almost $3 billion for the early shutdown of their plants.\r\n\r\nEnvironment Minister Steffi Lemke has dismissed suggestions that a new generation of nuclear power plants might prompt Germany to change course yet again.\r\n\r\n“Nuclear power plants remain high-risk facilities that produce highly radioactive atomic waste,” she told the Funke media group this week.\r\n\r\nA final decision has yet to be taken about where to store the most potent nuclear waste produced in German power plants. Experts say some material will remain dangerously radioactive for 35,000 generations.",
        "category": "world",
        "tag": "World",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "nuclear.jpg"
    },
    {
        "id": 54,
        "post_uid": "61d032862e132",
        "title": "Parents selling children shows desperation of Afghanistan",
        "slug": "parents-selling-children-shows-desperation-of-afghanistan",
        "summary": "SHEDAI CAMP, Afghanistan -- In a sprawling settlement of mud brick huts in western Afghanistan housing people displaced by drought and war, a woman is fighting to save her daughter.",
        "body": "Aziz Gul’s husband sold the 10-year-old girl into marriage without telling his wife, taking a down-payment so he could feed his family of five children. Without that money, he told her, they would all starve. He had to sacrifice one to save the rest.\r\n\r\nMany of Afghanistan’s growing number of destitute people are making desperate decisions such as these as their nation spirals into a vortex of poverty.\r\n\r\nThe aid-dependent country’s economy was already teetering when the Taliban seized power in mid-August amid a chaotic withdrawal of U.S. and NATO troops. The international community froze Afghanistan’s assets abroad and halted all funding, unwilling to work with a Taliban government given its reputation for brutality during its previous rule 20 years ago.\r\n\r\nThe consequences have been devastating for a country battered by four decades of war, a punishing drought and the coronavirus pandemic. Legions of state employees, including doctors, haven’t been paid in months. Malnutrition and poverty stalk the most vulnerable, and aid groups say more than half the population faces acute food shortages.\r\n\r\n“Day by day, the situation is deteriorating in this country, and especially children are suffering,” said Asuntha Charles, national director of the World Vision aid organization in Afghanistan, which runs a health clinic for displaced people just outside the western city of Herat.\r\n\r\n“Today I have been heartbroken to see that the families are willing to sell their children to feed other family members,” Charles said. “So it’s the right time for the humanitarian community to stand up and stay with the people of Afghanistan.”\r\n\r\nArranging marriages for very young girls is a frequent practice throughout the region. The groom’s family — often distant relatives — pays money to seal the deal, and the child usually stays with her own parents until she is at least around 15 or 16. Yet with many unable to afford even basic food, some say they’d allow prospective grooms to take very young girls or are even trying to sell their sons.\r\n\r\nBut Gul, unusually in this deeply patriarchal, male-dominated society, is resisting. Married off herself at 15, she says she would kill herself if her daughter, Qandi Gul, is forcibly taken away.\r\n\r\nGul remembers well the moment she found out her husband had sold Qandi. For around two months, the family had been able to eat. Eventually, she asked her husband where the money came from, and he told her.\r\n\r\n“My heart stopped beating. I wished I could have died at that time, but maybe God didn’t want me to die,” Gul said. Qandi sat close to her mother, her hazel eyes peering shyly from beneath her sky-blue headscarf. “Each time I remember that night ... I die and come back to life. It was so difficult.”\r\n\r\nShe asked her husband why he did it.\r\n\r\n“He said he wanted to sell one and save the others. ‘You all would have died this way,’ (he said.) I told him, ‘Dying was much better than what you have done.`”\r\n\r\nGul rallied her community, telling her brother and village elders that her husband had sold her child behind her back. They supported her, and with their help she secured a “divorce” for her child, but only on condition she repays the 100,000 afghanis (about $1,000) that her husband received.\r\n\r\nIt’s money she doesn’t have. Her husband fled, possibly fearing Gul might denounce him to the authorities. The Taliban government recently announced a ban on forcing women into marriage or using women and girls as exchange tokens to settle disputes.\r\n\r\nThe family of the prospective groom, a man of around 21 or 22, has already tried several times to claim the girl, she says. She is not sure how long she can fend them off.\r\n\r\n“I am just so desperate. If I can’t provide money to pay these people and can’t keep my daughter by my side, I have said that I will kill myself,” Gul said. “But then I think about the other children. What will happen to them? Who will feed them?” Her eldest is 12, her youngest — her sixth — just two months.\r\n\r\nNow alone, Gul leaves the children with her elderly mother while she goes to work in people’s homes. Her 12-year-old son works picking saffron after school. It’s barely enough to keep them fed, and the saffron season is short, only a few weeks in the fall.\r\n\r\n“We don’t have anything,” Gul said.\r\n\r\nIn another part of the same camp, father-of-four Hamid Abdullah was also selling his young daughters into arranged marriages, desperate for money to treat his chronically ill wife, pregnant with their fifth child.\r\n\r\nAbdullah borrowed money to pay for his wife’s treatments and can’t pay it back, he said. So three years ago, he received a down-payment for his eldest daughter Hoshran, now 7, in an arranged marriage to an 18-year-old in their native Badghis province. He’s now looking for someone to buy his second daughter, 6-year-old Nazia.\r\n\r\n“We don’t have food to eat,” Abdullah explained, adding he also had to buy medicine for his wife, who soon would need more treatment. “She needs another surgery, I don’t have one afghani to pay for the doctor.”\r\n\r\nThe family that bought Hoshran is waiting until she is older before the full amount is settled, he explained.\r\n\r\nBut he needs money now for food and treatments, so he is trying to arrange a marriage for Nazia for about 20,000-30,000 afghani ($200-$300).\r\n\r\n“What should we do? We have to do it, we have no other option,” said his wife, Bibi Jan. “When we made the decision, it was like someone had taken away a body part from me.”\r\n\r\nIn the neighboring province of Badghis, another displaced family is considering selling their son, 8-year-old Salahuddin.\r\n\r\nHis mother, Guldasta, said that after days with nothing to eat, she told her husband to take the boy to the bazaar and sell him to bring food for the others.\r\n\r\n“I don’t want to sell my son, but I have to,” the 35-year-old said. “No mother can do this to her child, but when you have no other choice, you have to make a decision against your will.”\r\n\r\nSalahuddin blinked and looked on silently. Surrounded by some of his seven brothers and sisters, his lip quivered slightly.\r\n\r\nHis father, Shakir, who is blind in one eye and has kidney problems, said the children had been crying for days from hunger. Twice, he said, he decided to take the boy to the bazaar and twice he faltered, unable to go through with it. “But now I think I have no other choice than to sell him.”\r\n\r\nBuying of boys is believed to be less common than girls, and when it does take place, it appears to be cases of infant boys bought by families who don’t have any sons. In her despair, Guldasta thought perhaps such a family would want an 8-year-old.\r\n\r\nThe desperation of millions is clear as more and more people face hunger. By the end of the year, some 3.2 million children under 5 years old are expected to suffer from acute malnutrition, according to the U.N.\r\n\r\nNazia is one of them. The 4-year-old lay listlessly in her mother’s arms after visiting the World Vision health clinic.\r\n\r\nTwo years ago, Nazia was a plump toddler, her mother Fatima said. Now, her emaciated limbs are just skin covering bone. Her little heart beats visibly beneath her ribcage.\r\n\r\n“The prices are high. Flour is expensive, cooking oil is expensive, everything is expensive,” Fatima said. “All day she is asking me to give her meat, yogurt and fruit. We don’t have anything, and we don’t have money to buy it for her.”\r\n\r\nCharles, World Vision’s national director for Afghanistan, said humanitarian aid funds are desperately needed.\r\n\r\n“I’m happy to see the pledges are made,” she said. But the pledges “shouldn’t stay as promises, they have to be seen as reality on the ground.”",
        "category": "world",
        "tag": "World",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "afgh.jpg"
    },
    {
        "id": 55,
        "post_uid": "61d032ed2bdbb",
        "title": "15 more migrants killed in Mexico crash return to Guatemala",
        "slug": "15-more-migrants-killed-in-mexico-crash-return-to-guatemala",
        "summary": "GUATEMALA CITY -- The bodies of 15 more migrants killed in a Dec. 9 truck crash in southern Mexico were flown home o Guatemala on Thursday.",
        "body": "The remains in brown wood-colored coffins were delivered by a Mexican military C-295 transport aircraft.\r\n\r\nThe coffins were unloaded at a Guatemalan base and handed over to their families. Most were expected to be buried in their hometowns Friday.\r\n\r\n“Today is a very sad day for Mexico, as we know it is for Guatemala,” said Laura Elena Carrillo, the director of Mexico`s international cooperation agency. “These people went looking for a dream, and today they return to rest in their own land.”\r\n\r\nThe Mexican government said that so far, 50 of the 56 migrants killed when a people smuggler`s semi-trailer truck rolled over on a highway have been identified. A total of 25 have been returned to their homelands, with another five expected to be returned soon, it said.\r\n\r\nOf the 50 identified dead, 37 were from Guatemala, 11 from the Dominican Republic, and one each from El Salvador and Ecuador.\r\n\r\nThe first four bodies of Guatemalan victims were returned earlier this month, and 18 more are to be returned later.\r\n\r\nAuthorities say fingerprints have been used to identify the bodies as well as relatives’ identification of their loved ones through photographs.\r\n\r\nMore than 100 migrants were injured in the crash, and Guatemalan authorities say 27 of them remain hospitalized.\r\n\r\nAssistant Guatemalan Foreign Minister Eduardo Hernández said some of those injured in the crash had resumed their trek north toward the United States despite the accident.\r\n\r\nThe truck was packed with as many as 250 migrants, and survivors said that speed and weight of the human cargo might have played a role in the crash.",
        "category": "world",
        "tag": "World",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "guatemala.jpg"
    },
    {
        "id": 56,
        "post_uid": "61d03381b7fb2",
        "title": "Requiem praise for South Africa`s Archbishop Desmond Tutu",
        "slug": "requiem-praise-for-south-africa`s-archbishop-desmond-tutu",
        "summary": "CAPE TOWN, South Africa -- A funeral service is underway in Cape Town, South Africa, for Archbishop Emeritus Desmond Tutu, the Nobel Peace Prize-winning equality activist who was revered in Africa for his role in ending apartheid.",
        "body": "“When we were in the dark, he brought light,” Archbishop of Canterbury Justin Welby, the head of the worldwide Anglican church, said in a video message shown at a requiem Mass celebrated in Tutu`s honor Saturday at St. George`s Cathedral.\r\n\r\n“For me to praise him is like a mouse giving tribute to an elephant,” Welby said. “South Africa has given us extraordinary examples of towering leaders of the rainbow nation with President Nelson Mandela and Archbishop Tutu.... Many Nobel winners` lights have grown dimmer over time, but Archbishop Tutu`s has grown brighter.”\r\n\r\nTutu`s small plain pine coffin, the cheapest available at his request to avoid any ostentatious displays, was the center of the service, which also is featuring African choirs, prayers and incense.\r\n\r\nSouth African President Cyril Ramaphosa is to give the eulogy at the service.\r\n\r\nFollowing the funeral, Tutu`s casket is to be taken away for cremation and his ashes interred at the cathedral`s columbarium.\r\n\r\nTutu died last Sunday at age 90.",
        "category": "world",
        "tag": "World",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "tutu.jpg"
    },
    {
        "id": 57,
        "post_uid": "61d035be37664",
        "title": "Rockets fired from Gaza land off central Israel`s coast",
        "slug": "rockets-fired-from-gaza-land-off-central-israel`s-coast",
        "summary": "JERUSALEM -- Rockets fired from the Hamas-ruled Gaza Strip on Saturday landed in the Mediterranean Sea off central Israel, the Israeli military said.",
        "body": "It was not immediately clear whether the rockets were meant to hit Israel, but Gaza-based militant groups often test-fire missiles toward the sea. There were no reports of casualties.\r\n\r\nApart from a single incident in September, there has been no cross-border rocket fire since a cease-fire ended an 11-day war between Israel and Hamas in May.\r\n\r\nIn a statement, the Israeli army said the rockets fell off the coast of the Tel Aviv Metropolitan Area. “According to protocol, no sirens were sounded and no interception took place,” it added.\r\n\r\nWitnesses in Gaza said they woke up to the sound of outgoing missiles around 7 a.m. and pictures circulated on social media showed whiffs of white smoke from the launching area.\r\n\r\nThe cease-fire, brokered by Egypt and other mediators, has been fragile. The militant Hamas group says Israel did not take serious steps to ease the blockade it imposed on Gaza with Egypt’s help when the Islamic movement seized control of the coastal enclave in 2007.\r\n\r\nTension are also high as other groups like the smaller but more hard-line Islamic Jihad threaten military escalation if Israel doesn’t end the administrative detention of a Palestinian prisoner who has been on a hunger strike for over 130 days.\r\n\r\nOn Wednesday, Palestinian militants in Gaza shot and lightly wounded an Israeli civilian near the security fence and Israel responded with tank fire targeting multiple Hamas sites in the first exchange of fire in months.",
        "category": "world",
        "tag": "World",
        "creator_uid": "61c42dab8c671",
        "date": "2021-12-31T21:00:00.000Z",
        "pic": "Gaza.png"
    }
];



module.exports=posts;